### ISSUE TITLE
Does your sample works with Node.js 0.12 version?

### ISSUE THREAD

**Issue by smartmouse** [ZiCog/node-tls-example#1]
Hi Node.js 0.12 has been available.

You are using an older version of NPM  node modules serialport  and it get issues with node.js 0.12

> serialport@1.1.3 install /home/nodebot/node-tls-example/node_modules/serialport
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/nodebot/node-tls-example/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../src/serialport.cpp:3:0:
../src/serialport.h:28:34: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.h:28:49: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/serialport.h:29:15: error: variable or field ‘EIO_List’ declared void
../src/serialport.h:29:15: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:29:26: error: ‘req’ was not declared in this scope
../src/serialport.h:30:20: error: variable or field ‘EIO_AfterList’ declared void
../src/serialport.h:30:20: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:30:31: error: ‘req’ was not declared in this scope
../src/serialport.h:32:34: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.h:32:49: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/serialport.h:33:15: error: variable or field ‘EIO_Open’ declared void
../src/serialport.h:33:15: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:33:26: error: ‘req’ was not declared in this scope
../src/serialport.h:34:20: error: variable or field ‘EIO_AfterOpen’ declared void
../src/serialport.h:34:20: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:34:31: error: ‘req’ was not declared in this scope
In file included from ../src/serialport.cpp:3:0:
../src/serialport.h:37:35: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.h:37:50: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/serialport.h:38:16: error: variable or field ‘EIO_Write’ declared void
../src/serialport.h:38:16: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:38:27: error: ‘req’ was not declared in this scope
../src/serialport.h:39:21: error: variable or field ‘EIO_AfterWrite’ declared void
../src/serialport.h:39:21: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:39:32: error: ‘req’ was not declared in this scope
../src/serialport.h:41:35: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.h:41:50: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/serialport.h:42:16: error: variable or field ‘EIO_Close’ declared void
../src/serialport.h:42:16: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:42:27: error: ‘req’ was not declared in this scope
../src/serialport.h:43:21: error: variable or field ‘EIO_AfterClose’ declared void
../src/serialport.h:43:21: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:43:32: error: ‘req’ was not declared in this scope
../src/serialport.h:45:35: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.h:45:50: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/serialport.h:46:16: error: variable or field ‘EIO_Flush’ declared void
../src/serialport.h:46:16: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:46:27: error: ‘req’ was not declared in this scope
../src/serialport.h:47:21: error: variable or field ‘EIO_AfterFlush’ declared void
../src/serialport.h:47:21: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.h:47:32: error: ‘req’ was not declared in this scope
../src/serialport.h:82:3: error: ‘uv_work_t’ does not name a type
../src/serialport.h:83:3: error: ‘ngx_queue_t’ does not name a type
../src/serialport.cpp:9:1: error: ‘uv_mutex_t’ does not name a type
../src/serialport.cpp:10:1: error: ‘ngx_queue_t’ does not name a type
../src/serialport.cpp:12:34: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/serialport.cpp:12:49: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handlev8::Value Open(const int&)
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is p
../src/serialport.cpp:13:19: error: within this context
../src/serialport.cpp:15:18: error: ‘write_queue_mutex’ was not declared in this scope
../src/serialport.cpp:15:35: error: ‘uv_mutex_init’ was not declared in this scope
../src/serialport.cpp:16:19: error: ‘write_queue’ was not declared in this scope
../src/serialport.cpp:16:30: error: ‘ngx_queue_init’ was not declared in this scope
../src/serialport.cpp:19:13: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:20:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/serialport.cpp:20:24: error: ‘ThrowException’ is not a member of ‘v8’
../src/serialport.cpp:20:68: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:22:36: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:25:13: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:26:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/serialport.cpp:26:24: error: ‘ThrowException’ is not a member of ‘v8’
../src/serialport.cpp:26:68: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:28:41: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:31:13: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:32:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/serialport.cpp:32:24: error: ‘ThrowException’ is not a member of ‘v8’
../src/serialport.cpp:32:68: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:34:41: error: invalid types ‘const int[int]’ for array subscript
../src/serialport.cpp:39:34: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:40:34: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:41:36: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:42:45: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:43:48: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:44:37: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:45:60: error: no matching function for call to ‘v8::Persistentv8::Value::New(v8:
../src/serialport.cpp:45:60: note: candidate is:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note: static T\* v8::PersistentBase<T>::New(v = v8::Value]
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 pro
../src/serialport.cpp:46:69: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:47:77: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:48:70: error: ‘New’ is not a member of ‘v8::String’
../src/serialport.cpp:50:3: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.cpp:50:14: error: ‘req’ was not declared in this scope
../src/serialport.cpp:50:24: error: expected type-specifier before ‘uv_work_t’
../src/serialport.cpp:50:24: error: expected ‘;’ before ‘uv_work_t’
../src/serialport.cpp:52:33: error: ‘uv_default_loop’ was not declared in this scope
../src/serialport.cpp:52:41: error: ‘EIO_Open’ was not declared in this scope
../src/serialport.cpp:52:52: error: ‘uv_after_work_cb’ was not declared in this scope
../src/serialport.cpp:52:82: error: ‘uv_queue_work’ was not declared in this scope
../src/serialport.cpp:54:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/serialport.cpp:54:36: error: too few arguments to function ‘v8::Handlev8::Primitive v8::Undefin
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
../src/serialport.cpp: At global scope:
../src/serialport.cpp:57:20: error: variable or field ‘EIO_AfterOpen’ declared void
../src/serialport.cpp:57:20: error: ‘uv_work_t’ was not declared in this scope
../src/serialport.cpp:57:31: error: ‘req’ was not declared in this scope
../src/serialport.cpp: In function ‘v8::Handlev8::Value Open(const int&)’:
../src/serialport.cpp:55:1: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [Release/obj.target/serialport/src/serialport.o] Error 1

But if you use the latest version of serialport , it should compile fine.
Question: are you planning to support node.js v0.12 for your example?

Thanks for creating this example.
Thanks

**Comment by ZiCog** [comment]
Clients and servers for TLS and HTTPS have been updated to work with node 0.12.0.

Seems to be working will close issue when confirmed.

**Comment by smartmouse** [comment]
@Thank you, you are awesome! it is resolved with node 1.2 .
(a side question, to run the test  for the DNS agent1, we do not have permission to modify the etc/host,
Eeek: Error: getaddrinfo ENOTFOUND agent1, any other way to workaround? )
Thanks in advance.

**Comment by ZiCog** [comment]
Hmmm....I guess the best thing to do is get yourself a domain name(s) that will show up in public DNS servers.

I have done that by signing up for the free DNS service at http://freedns.afraid.org/. Though them I have the domain name the.linuxd.org.

Alternatively...I just tried an experiment. Basically in the ssl/make-certs.sh file replace all occurrences of "agent1" with the IP address. In my case "192.168.1.194". Then run that to make the certs. 

I end up with files 192.168.1.194-cert.pem,  192.168.1.194-csr.pem and  192.168.1.194-key.pem which I copy to the keys directory. 

Then I replaced "agent1" with that IP address in run-tls-client.js and tls-server.js

To my surprise this works!

So, it turns out we don't need DNS at all. 

This is not satisfactory as IP addresses tend to change and then you have to rebuild and redistribute the certs.

I have no idea if using raw IP addresses has any impact on the security of the system in the end.
